name: Fetch RSS and Update Articles

on:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install feedparser
        run: pip install feedparser

      - name: Fetch and filter RSS
        run: |
          python scripts/fetch_rss.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add articles.json
          git commit -m "Update articles.json from RSS" || echo "No changes"
          git push
