name: Update Articles JSON Hourly

# Trigger: every hour
on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:      # also allows manual trigger

jobs:
  update_articles:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (needed for script)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 3: Install dependencies (if any)
      - name: Install dependencies
        run: npm install node-fetch@3

      # Step 4: Run script to fetch new articles and append
      - name: Update articles.json
        run: |
          node <<'EOF'
          import fs from 'fs';
          import fetch from 'node-fetch';

          const path = 'articles.json';
          let articles = [];
          if (fs.existsSync(path)) {
            const data = fs.readFileSync(path, 'utf-8');
            articles = JSON.parse(data);
          }

          // Example: fetch new articles from RSS or API
          // Replace the URL with your actual news source endpoint
          const response = await fetch('https://example.com/latest-news.json');
          const newArticles = await response.json();

          // Append articles if not already present
          newArticles.forEach(a => {
            // Check if title already exists
            if (!articles.some(existing => existing.title === a.title)) {
              articles.push({
                source: a.source || '',
                title: a.title || '',
                link: a.link || '',
                image: a.image || null,
                shown: false      // default
              });
            }
          });

          // Save updated JSON
          fs.writeFileSync(path, JSON.stringify(articles, null, 2));
          EOF

      # Step 5: Commit and push changes
      - name: Commit and push updated articles.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add articles.json
          git commit -m "Update articles.json via hourly workflow" || echo "No changes to commit"
          git push
