name: Update RSS Articles

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:   # also allows manual run

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser textblob nltk
      - name: Run RSS scraper
        run: |
          python ToughNews.py
      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add articles.json
          git commit -m "Update articles"
          git push
