name: Update Articles JSON Hourly

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:      # also allows manual trigger

jobs:
  update_articles:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Install requirements if any
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Add any dependencies here if needed, e.g.,
          # pip install requests feedparser

      # 4. Run the ToughNews.py script
      - name: Run ToughNews.py
        run: |
          python ToughNews.py

      # 5. Commit and push updated articles.json
      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add articles.json
          git commit -m "Update articles.json via hourly workflow" || echo "No changes to commit"
          git push
