name: Update Articles

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # every hour

jobs:
  update-articles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser textblob nltk

      - name: Download NLTK punkt
        run: python -m nltk.downloader punkt

      - name: Run scraper
        run: python ToughNews.py

      - name: Commit & push updates
        run: |
          git add articles.json archive.json
          git diff --cached --quiet || git commit -m "Update articles"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
