name: ToughNews

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ToughNews
        run: python ToughNews.py

      - name: Force shown=false for all new articles
        run: |
          python - <<'PYCODE'
          import json, pathlib
          path = pathlib.Path("archive.json")
          if path.exists():
              data = json.loads(path.read_text(encoding="utf-8"))
              for a in data:
                  a["shown"] = False
              path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
          PYCODE

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add archive.json
          git commit -m "Update archive.json with new articles" || echo "No changes"
          git push
