name: Update Articles

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:      # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser textblob nltk requests

    - name: Download nltk punkt
      run: |
        python -m textblob.download_corpora
        python -m nltk.downloader punkt

    - name: Run ToughNews script
      run: python ToughNews.py

    - name: Commit and push updated articles.json 
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add articles.json archive.json
        git commit -m "Update articles" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

